// Mock Data Generator
import { CalendarEvent, WBSProject, WBSTask, ChatMessage } from '../types'
import { addDays, addHours, startOfWeek, addMinutes } from 'date-fns'

const COLORS = {
  work: '#3B82F6',
  personal: '#8B5CF6',
  project: '#F59E0B',
  health: '#10B981',
  social: '#EC4899',
  focus: '#6366F1',
}

export const generateMockEvents = (): CalendarEvent[] => {
  const now = new Date()
  const weekStart = startOfWeek(now, { weekStartsOn: 1 })

  return [
    {
      id: 'evt-1',
      title: 'Product Launch Planning',
      description: 'Q1 2026 製品ローンチの戦略会議',
      start: addHours(weekStart, 10),
      end: addHours(weekStart, 12),
      category: 'work',
      color: COLORS.work,
      priority: 'critical',
      attendees: ['田中 太郎', '鈴木 花子', '山田 次郎'],
      location: '会議室 A',
      tags: ['product', 'strategy'],
    },
    {
      id: 'evt-2',
      title: 'Deep Work: API設計',
      description: 'バックエンドAPIアーキテクチャの設計',
      start: addHours(addDays(weekStart, 1), 9),
      end: addHours(addDays(weekStart, 1), 12),
      category: 'focus',
      color: COLORS.focus,
      priority: 'high',
      tags: ['coding', 'architecture'],
    },
    {
      id: 'evt-3',
      title: 'Team Standup',
      description: '毎朝のデイリーミーティング',
      start: addHours(addDays(weekStart, 1), 9),
      end: addHours(addDays(weekStart, 1), 9.5),
      category: 'work',
      color: COLORS.work,
      priority: 'medium',
      recurring: 'daily',
      attendees: ['チーム全員'],
    },
    {
      id: 'evt-4',
      title: 'Yoga & Meditation',
      description: '朝のマインドフルネスセッション',
      start: addHours(addDays(weekStart, 2), 7),
      end: addHours(addDays(weekStart, 2), 8),
      category: 'health',
      color: COLORS.health,
      priority: 'medium',
      recurring: 'daily',
    },
    {
      id: 'evt-5',
      title: 'UI/UXレビュー',
      description: 'プロダクトデザインのフィードバックセッション',
      start: addHours(addDays(weekStart, 2), 14),
      end: addHours(addDays(weekStart, 2), 16),
      category: 'project',
      color: COLORS.project,
      priority: 'high',
      attendees: ['デザインチーム'],
      wbsId: 'proj-1',
    },
    {
      id: 'evt-6',
      title: 'ランチ 🍜',
      description: '同僚と六本木でランチ',
      start: addHours(addDays(weekStart, 3), 12),
      end: addHours(addDays(weekStart, 3), 13),
      category: 'social',
      color: COLORS.social,
      priority: 'low',
    },
    {
      id: 'evt-7',
      title: 'プロジェクト進捗報告',
      description: '経営陣へのマイルストーン報告',
      start: addHours(addDays(weekStart, 3), 15),
      end: addHours(addDays(weekStart, 3), 16.5),
      category: 'work',
      color: COLORS.work,
      priority: 'critical',
      attendees: ['CEO', 'CTO', 'PM'],
      wbsId: 'proj-1',
    },
    {
      id: 'evt-8',
      title: 'コードレビュー',
      description: 'PRレビューとマージ',
      start: addHours(addDays(weekStart, 4), 10),
      end: addHours(addDays(weekStart, 4), 11.5),
      category: 'work',
      color: COLORS.work,
      priority: 'high',
    },
    {
      id: 'evt-9',
      title: 'ウィークリーリトリート',
      description: '週次振り返りと次週計画',
      start: addHours(addDays(weekStart, 4), 17),
      end: addHours(addDays(weekStart, 4), 18),
      category: 'personal',
      color: COLORS.personal,
      priority: 'medium',
    },
    {
      id: 'evt-10',
      title: 'Family Dinner 🏡',
      description: '家族との特別ディナー',
      start: addHours(addDays(weekStart, 5), 18),
      end: addHours(addDays(weekStart, 5), 20),
      category: 'personal',
      color: COLORS.personal,
      priority: 'high',
    },
    {
      id: 'evt-11',
      title: 'Sprint Planning',
      description: '次のスプリントの計画と優先度設定',
      start: addHours(addDays(weekStart, 7), 10),
      end: addHours(addDays(weekStart, 7), 12),
      category: 'project',
      color: COLORS.project,
      priority: 'high',
      wbsId: 'proj-2',
    },
    {
      id: 'evt-12',
      title: 'Investor Meeting',
      description: 'シリーズBラウンドの投資家ミーティング',
      start: addHours(addDays(weekStart, 8), 14),
      end: addHours(addDays(weekStart, 8), 16),
      category: 'work',
      color: COLORS.work,
      priority: 'critical',
      location: 'オンライン (Zoom)',
    },
    {
      id: 'evt-13',
      title: '読書タイム 📚',
      description: '技術書・ビジネス書の集中読書',
      start: addHours(now, 1),
      end: addHours(now, 2),
      category: 'personal',
      color: COLORS.personal,
      priority: 'low',
    },
    {
      id: 'evt-14',
      title: '1on1 with Manager',
      description: 'キャリア開発とフィードバック',
      start: addHours(addDays(weekStart, 9), 11),
      end: addHours(addDays(weekStart, 9), 12),
      category: 'work',
      color: COLORS.work,
      priority: 'medium',
    },
  ]
}

export const generateMockProjects = (): WBSProject[] => {
  const now = new Date()

  const proj1Tasks: WBSTask[] = [
    {
      id: 'task-1-1',
      title: '要件定義・仕様書作成',
      description: 'プロダクトの機能要件と非機能要件を文書化する',
      status: 'done',
      priority: 'critical',
      progress: 100,
      estimatedHours: 16,
      actualHours: 18,
      startDate: addDays(now, -14),
      dueDate: addDays(now, -10),
      completedAt: addDays(now, -9),
      tags: ['docs', 'planning'],
      assignee: '田中 太郎',
    },
    {
      id: 'task-1-2',
      title: 'UIデザイン・プロトタイプ',
      description: 'Figmaでワイヤーフレームとプロトタイプを作成',
      status: 'done',
      priority: 'high',
      progress: 100,
      estimatedHours: 24,
      actualHours: 20,
      startDate: addDays(now, -10),
      dueDate: addDays(now, -5),
      completedAt: addDays(now, -6),
      tags: ['design', 'figma'],
      assignee: '鈴木 花子',
    },
    {
      id: 'task-1-3',
      title: 'フロントエンド実装',
      description: 'React + TypeScriptによるUI実装',
      status: 'in_progress',
      priority: 'high',
      progress: 65,
      estimatedHours: 40,
      actualHours: 26,
      startDate: addDays(now, -5),
      dueDate: addDays(now, 5),
      tags: ['react', 'typescript', 'frontend'],
      assignee: '山田 次郎',
    },
    {
      id: 'task-1-4',
      title: 'バックエンドAPI開発',
      description: 'Hono + D1によるREST API実装',
      status: 'in_progress',
      priority: 'high',
      progress: 40,
      estimatedHours: 48,
      actualHours: 19,
      startDate: addDays(now, -3),
      dueDate: addDays(now, 7),
      tags: ['api', 'backend', 'hono'],
      assignee: '佐藤 健太',
    },
    {
      id: 'task-1-5',
      title: 'テスト・QA',
      description: 'ユニットテスト・E2Eテストの実装と実行',
      status: 'todo',
      priority: 'medium',
      progress: 0,
      estimatedHours: 20,
      startDate: addDays(now, 5),
      dueDate: addDays(now, 12),
      tags: ['testing', 'qa'],
      assignee: '伊藤 美咲',
    },
    {
      id: 'task-1-6',
      title: '本番環境デプロイ',
      description: 'Cloudflare Pagesへのデプロイとインフラ設定',
      status: 'todo',
      priority: 'high',
      progress: 0,
      estimatedHours: 8,
      startDate: addDays(now, 12),
      dueDate: addDays(now, 14),
      tags: ['deployment', 'infra'],
      dependencies: ['task-1-5'],
    },
    {
      id: 'task-1-7',
      title: 'ローンチ準備・マーケティング',
      description: 'プレスリリース、SNS投稿、ドキュメント整備',
      status: 'blocked',
      priority: 'medium',
      progress: 15,
      estimatedHours: 12,
      dueDate: addDays(now, 14),
      tags: ['marketing', 'launch'],
      dependencies: ['task-1-6'],
      notes: '法務確認待ち',
    },
  ]

  const proj2Tasks: WBSTask[] = [
    {
      id: 'task-2-1',
      title: 'データモデル設計',
      description: 'スキーマ設計とER図作成',
      status: 'done',
      priority: 'critical',
      progress: 100,
      estimatedHours: 10,
      actualHours: 8,
      dueDate: addDays(now, -7),
      completedAt: addDays(now, -8),
      assignee: '田中 太郎',
    },
    {
      id: 'task-2-2',
      title: 'AIモデル統合調査',
      description: 'Claude / GPT-4 APIの評価と選定',
      status: 'in_progress',
      priority: 'high',
      progress: 50,
      estimatedHours: 16,
      actualHours: 8,
      dueDate: addDays(now, 3),
      assignee: '鈴木 花子',
    },
    {
      id: 'task-2-3',
      title: 'MVP実装',
      description: 'コア機能の最小実装',
      status: 'todo',
      priority: 'high',
      progress: 0,
      estimatedHours: 60,
      startDate: addDays(now, 4),
      dueDate: addDays(now, 18),
    },
    {
      id: 'task-2-4',
      title: 'ユーザーテスト',
      description: '5名のベータユーザーによるテスト',
      status: 'todo',
      priority: 'medium',
      progress: 0,
      estimatedHours: 12,
      startDate: addDays(now, 18),
      dueDate: addDays(now, 25),
    },
  ]

  return [
    {
      id: 'proj-1',
      title: 'Lumina 製品ローンチ',
      description: 'AI搭載カレンダーアプリのマーケットローンチ',
      color: '#3B82F6',
      eventId: 'evt-1',
      tasks: proj1Tasks,
      createdAt: addDays(now, -14),
      updatedAt: now,
      dueDate: addDays(now, 14),
      progress: 52,
    },
    {
      id: 'proj-2',
      title: 'AI機能開発 Sprint 3',
      description: 'チャットボット・自動スケジューリング機能の実装',
      color: '#F59E0B',
      eventId: 'evt-11',
      tasks: proj2Tasks,
      createdAt: addDays(now, -7),
      updatedAt: now,
      dueDate: addDays(now, 25),
      progress: 35,
    },
  ]
}

export const generateMockMessages = (): ChatMessage[] => {
  const now = new Date()
  return [
    {
      id: 'msg-1',
      role: 'assistant',
      content: 'こんにちは！LuminaのAIアシスタントです ✨\n\n今日のスケジュールを確認しましたが、**3つの重要なタスク**があります。\n\n- 🔴 Product Launch Planningまで**2日**\n- 🟡 フロントエンド実装が65%完了\n- ⚡ 今週のDeep Workセッションを設定しましょうか？',
      timestamp: addMinutes(now, -30),
      actions: [
        { id: 'a1', label: '今週の計画を最適化', type: 'navigate', payload: { view: 'week' } },
        { id: 'a2', label: 'WBSを自動生成', type: 'create_wbs', payload: {} },
      ],
    },
  ]
}
